name: Update Major Release Tag

on:
  release:
    types: [published, created]

permissions:
  contents: write

jobs:
  movetag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Exit if manual test release
        uses: actions/github-script@v6
        env: 
          VERSION: ${GITHUB_REF#refs/tags/}
        with:
          script: |
            const release_tag = process.env.VERSION;
            if (release_tag.match(/^releases\/v\d{10}$/)) {
              console.log("This is a manual test release. Exiting without updating major version tag.");
              process.exit(1);
            }

      - name: Get major version num and update tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR=${VERSION%%.*}
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag -fa "${MAJOR}" -m 'Update major version tag to point at ${GITHUB_REF}'
          git push origin "${MAJOR}" --force
