name: Test Create PR and Create Release Notes Actions

on:
  workflow_dispatch:
    inputs:
      feature-branch:
        description: "The name of the feature branch to test with"
        required: true
        default: "main"

permissions:
  contents: write
  pull-requests: write

jobs:
  manual-tests:
    runs-on: ubuntu-latest
    outputs:
      pull-request-url: ${{ steps.create_pr.outputs.pull-request-url }}
      pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
      release-id: ${{ steps.create_release_notes.outputs.release-id }}
      release-branch: ${{ steps.generate_branch_name.outputs.release-branch }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.feature-branch }}
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Generate a unique release branch name
        id: generate_branch_name
        run: |
          export RELEASE_BRANCH="releases/v$(date +%s)-test"
          echo "release-branch=$RELEASE_BRANCH" >> $GITHUB_OUTPUT

      - name: Create files and commits
        run: |
          git checkout -b ${{ steps.generate_branch_name.outputs.release-branch }}
          git config user.name "Test User"
          git config user.email "testuser@example.com"
          echo "dummy content" > OVP1234.txt
          git add OVP1234.txt && git commit -m "OVP-1234: Add dummy file for testing"
          echo "dummy content" > OVP5678.txt
          git add OVP5678.txt && git commit -m "OVP-5678: Add another dummy file for testing"
          git push origin ${{ steps.generate_branch_name.outputs.release-branch }}

      - name: Run create-pr action
        id: create_pr
        uses: ./create-pr
        with:
          base-branch: "main"
          target-branch: ${{ steps.generate_branch_name.outputs.release-branch }}
          github-token: ${{ secrets.PAT }}

      - name: Run create-release-notes action
        id: create_release_notes
        uses: ./create-release-notes
        with:
          base-branch: "main"
          release-branch: "${{ steps.generate_branch_name.outputs.release-branch }}"
          confluence-space: "kaisunraj"
          github-token: ${{ secrets.PAT }}
          generate-github-release: "true"

      - name: Sleep to allow verification of draft release
        run: sleep 15 # Sleep for 15 seconds to allow manual verification of the created draft release

      - name: Run create-release-notes action with same base and target branch
        id: create_release_notes_same_branch
        uses: ./create-release-notes
        with:
          base-branch: "main"
          release-branch: "main"
          confluence-space: "kaisunraj"
          github-token: ${{ secrets.PAT }}
          generate-github-release: "true"

      - name: Run print only version
        id: create_release_notes_print
        uses: ./create-release-notes
        with:
          base-branch: "main"
          release-branch: "${{ steps.generate_branch_name.outputs.release-branch }}"
          confluence-space: "kaisunraj"
          github-token: ${{ secrets.PAT }}
          generate-github-release: "false"

  teardown:
    runs-on: ubuntu-latest
    needs: manual-tests
    steps:
      - name: Wait to allow manual verification
        run: sleep 30 # Wait for 30 seconds to allow manual verification of the created PR and release notes

      - name: Close created PR
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls/${{ needs.manual-tests.outputs.pull-request-number }} \
            -d '{"state": "closed"}'

      - name: Delete created branch
        run: |
          curl -X DELETE \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/git/refs/heads/${{ needs.manual-tests.outputs.release-branch }}

      - name: Delete release
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases/${{ needs.manual-tests.outputs.release-id }}

      - name: Delete tag
        run: |
          curl -X DELETE \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/git/refs/tags/${{ needs.manual-tests.outputs.release-branch }}
